# Generated by Django 5.0.7 on 2024-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventtype_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(default="123 Test street, CB1 GB1", max_length=255),
            preserve_default=False,
        ),
    ]
