# Generated by Django 5.0.7 on 2024-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_delete_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
