# Generated by Django 5.0.7 on 2024-08-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="average_rating_loudness",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
