# Generated by Django 5.0.7 on 2024-08-30 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_ratingtype_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("event", "user", "rating_type")},
        ),
    ]
