# Generated by Django 5.0.7 on 2024-08-30 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="events.event",
            ),
            preserve_default=False,
        ),
    ]
