# Generated by Django 5.0.7 on 2024-08-30 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_comment_comment_alter_comment_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
