# Generated by Django 5.0.7 on 2024-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_comment_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
