# Generated by Django 5.0.7 on 2024-08-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_alter_comment_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="address",
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.JSONField(default=dict),
        ),
    ]
