# Generated by Django 5.0.7 on 2024-08-31 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_location_remove_event_address_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="events.location",
            ),
        ),
    ]
