# Generated by Django 5.0.7 on 2024-08-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_alter_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
