# Generated by Django 5.0.7 on 2025-05-23 19:26

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_event_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="location",
            name="lng",
        ),
        migrations.AddField(
            model_name="location",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                null=True,
                srid=4326,
            ),
        ),
    ]
