# Generated by Django 5.0.7 on 2024-08-01 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = []
