# Generated by Django 5.0.7 on 2024-08-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
